### ISSUE TITLE
Repository requires submodules not available publically

### ISSUE THREAD

**Issue by fatadama** [uf-reef-avl/reef_estimator_bundle#1]
As an outside user, I am unable to set up all the submodules included in this repository. I can get as far as "odom_to_velocity" before I'm prompted for a GitHub username and password. I tried using mine, and I get "remote: repository not found", indicating either the remote does not exist, or I don't have access to it.

I was able to get the parts I was interested to compile by manually downloading the dependencies, but if this repository is intended for public use, you might want to update it.

**Comment by prasgane** [comment]
@fatadama thank for pointing that out. I have fixed the submodules now and it should work now.
